USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_PRICESCOPE
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PRICESCOPE;
CREATE SCHEMA IF NOT EXISTS PRICESCOPE.RAW;

USE WAREHOUSE WH_PRICESCOPE;
USE SCHEMA PRICESCOPE.RAW;


CREATE OR REPLACE FILE FORMAT FF_PARQUET
  TYPE = PARQUET;

CREATE OR REPLACE FILE FORMAT FF_JSON
  TYPE = JSON;

CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

CREATE OR REPLACE STAGE STG_AZURE_RAW
  URL = 'azure://stpricescope2026.blob.core.windows.net/raw/'
  CREDENTIALS = (AZURE_SAS_TOKEN = '<AZURE_SAS_TOKEN from .env>');

LIST @STG_AZURE_RAW;