COPY INTO RAW_PRODUCTS
FROM @STG_AZURE_RAW/master/products.parquet
FILE_FORMAT = (FORMAT_NAME = FF_PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _LOADED_AT = METADATA$START_SCAN_TIME);

COPY INTO RAW_STORES
FROM @STG_AZURE_RAW/master/stores.parquet
FILE_FORMAT = (FORMAT_NAME = FF_PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _LOADED_AT = METADATA$START_SCAN_TIME);

COPY INTO RAW_PRICE_HISTORY
FROM @STG_AZURE_RAW/master/price_history.parquet
FILE_FORMAT = (FORMAT_NAME = FF_PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _LOADED_AT = METADATA$START_SCAN_TIME);

COPY INTO RAW_PROMOTIONS
FROM @STG_AZURE_RAW/master/promotions.parquet
FILE_FORMAT = (FORMAT_NAME = FF_PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _LOADED_AT = METADATA$START_SCAN_TIME);

COPY INTO RAW_POS_SALES
FROM @STG_AZURE_RAW/sales/
FILE_FORMAT = (FORMAT_NAME = FF_PARQUET)
PATTERN = '.*[.]parquet'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (_SOURCE_FILE = METADATA$FILENAME, _LOADED_AT = METADATA$START_SCAN_TIME);

COPY INTO RAW_COMPETITOR_PRICES (RAW_JSON, _SOURCE_FILE, _LOADED_AT)
FROM (
  SELECT $1, METADATA$FILENAME, CURRENT_TIMESTAMP()
  FROM @STG_AZURE_RAW/competitor/
)
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
PATTERN = '.*[.]json';

COPY INTO RAW_WEATHER (RAW_JSON, _SOURCE_FILE, _LOADED_AT)
FROM (
  SELECT $1, METADATA$FILENAME, CURRENT_TIMESTAMP()
  FROM @STG_AZURE_RAW/weather/weather_berlin.json
)
FILE_FORMAT = (FORMAT_NAME = FF_JSON);