SELECT 'RAW_PRODUCTS'          AS table_name, COUNT(*) AS row_count FROM RAW_PRODUCTS
UNION ALL SELECT 'RAW_STORES',            COUNT(*) FROM RAW_STORES
UNION ALL SELECT 'RAW_PRICE_HISTORY',     COUNT(*) FROM RAW_PRICE_HISTORY
UNION ALL SELECT 'RAW_PROMOTIONS',        COUNT(*) FROM RAW_PROMOTIONS
UNION ALL SELECT 'RAW_POS_SALES',         COUNT(*) FROM RAW_POS_SALES
UNION ALL SELECT 'RAW_COMPETITOR_PRICES', COUNT(*) FROM RAW_COMPETITOR_PRICES
UNION ALL SELECT 'RAW_WEATHER',           COUNT(*) FROM RAW_WEATHER;

SELECT _SOURCE_FILE, COUNT(*) 
FROM RAW_POS_SALES 
GROUP BY 1 ORDER BY 1 LIMIT 5;

SELECT CURRENT_USER(), CURRENT_ACCOUNT(), CURRENT_ROLE();